# Experiment name - all outputs will be under ./experiments/{experiment_name}/
experiment_name: scaling_exp_depth_001

# Shared parameters for all runs
activation: relu
num_epochs: 25
outer_iterations: 55
seed: 0

# Success threshold for max_ae
max_ae_threshold: 0.001

# Initial K value for num_samples
initial_k: 2500

# Maximum K to try before giving up on a tuple
max_k: 100000000

# Number of GPUs for parallel sample generation and training
num_gpus: 1

# Number of students in population
population_size: 10

# List of [layers, dataset] tuples - SORTED EASIEST TO HARDEST
configurations:
  # MNIST configs
  - layers: [784, 128, 10]
    dataset: mnist
  - layers: [784, 128, 64, 10]
    dataset: mnist
  - layers: [784, 128, 64,32, 10]
    dataset: mnist
  - layers: [784, 128, 80, 40,32, 10]
    dataset: mnist
  - layers: [784, 128, 80, 40,32, 16, 10]
    dataset: mnist

