EXPERIMENT:
  NAME: "CD on cifar100, KL divergence loss on student/teacher raw logits"
  TAG: "CD,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
DATASET:
  NUM_WORKERS: 8
SOLVER:
  BATCH_SIZE: 1028
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [75, 150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "cd"
CD:
  POPULATION_SIZE: 5
  SAMPLES_PER_EPOCH: 1028
  EPOCHS: 1028
  SCHEDULE: [300, 600, 900] 
  SAMPLE_INIT: "image"
